name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake Contribution SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Prakhar-Jaiswal17  # Your GitHub username

      - name: Commit SVG to repo
        run: |
          cp github-contribution-grid-snake.svg README/
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add README/github-contribution-grid-snake.svg
          git commit -m "Update contribution snake"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
